name: Release usersh

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: usersh
            name: usersh-linux-amd64
            
          - release_for: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: usersh
            name: usersh-macos-amd64
            
          - release_for: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            bin: usersh
            name: usersh-macos-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.platform.target }}
        
      - name: Prepare binary
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ${{ matrix.platform.name }}.tar.gz ${{ matrix.platform.bin }}
          
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
